In [26]:
import numpy as np

In [27]:
def softmax(x):
    e_x = np.exp(x - np.max(x))  # subtract max(x) for numerical stability
    return e_x / e_x.sum(axis=0)  # sum along the column

In [28]:
# Define the neural network architecture
input_size = 2
hidden_size = 3
output_size = 2

# Initialize the weights and biases
np.random.seed(0)
W1 = np.array([[0.1, 0.3], [0.2, 0.4], [-0.5, -0.2]])  # weight matrix for the first layer
b1 = np.array([0.1, 0.2, -0.1])  # bias vector for the first layer
W2 = np.array([[0.3, -0.5, 0.1], [-0.2, 0.4, 0.2]])  # weight matrix for the second layer
b2 = np.array([0.1, -0.1])  # bias vector for the second layer

# Print the updated weights and biases
print("Weights:")
print("W1:", W1)
print("W2:", W2)
print("Biases:")
print("b1:", b1)
print("b2:", b2)

Weights:
W1: [[ 0.1  0.3]
 [ 0.2  0.4]
 [-0.5 -0.2]]
W2: [[ 0.3 -0.5  0.1]
 [-0.2  0.4  0.2]]
Biases:
b1: [ 0.1  0.2 -0.1]
b2: [ 0.1 -0.1]


In [29]:
# Forward propagation
x = np.array([0.5, 0.6])   # input data
y_true = np.array([0, 1])  # true output

z1 = np.dot(W1, x) + b1
print(z1)
h1 = np.maximum(0, z1)
print(h1)
z2 = np.dot(W2, h1) + b2
print(z2)
y_hat = softmax(z2)
print(y_hat)

[ 0.33  0.54 -0.47]
[0.33 0.54 0.  ]
[-0.071  0.05 ]
[0.46978685 0.53021315]


In [30]:
dZ2 = (y_hat - y_true).reshape(-1, 1)
print(dZ2)
h1 = h1.reshape(-1, 1)

# Backpropagation - compute the gradients of each parameter
dW2 = np.dot(dZ2, h1.T)
db2 = dZ2

dh1 = np.dot(W2.T, dZ2)
dz1 = np.multiply(dh1, (h1 > 0)) 
dW1 = np.dot(dz1, x.reshape(-1, 1).T)
db1 = dz1

[[ 0.46978685]
 [-0.46978685]]


In [31]:
# Update weights
learning_rate = 0.1
W2 = W2 - learning_rate * dW2
b2 = b2 - learning_rate * db2
W1 = W1 - learning_rate * dW1
b1 = b1 - learning_rate * db1

In [32]:
# Print the updated weights and biases
print("Updated Weights:")
print("W1:", W1)
print("W2:", W2)
print("Updated Biases:")
print("b1:", b1)
print("b2:", b2)


Updated Weights:
W1: [[ 0.08825533  0.28590639]
 [ 0.22114041  0.42536849]
 [-0.5        -0.2       ]]
W2: [[ 0.28449703 -0.52536849  0.1       ]
 [-0.18449703  0.42536849  0.2       ]]
Updated Biases:
b1: [[ 0.07651066  0.17651066 -0.12348934]
 [ 0.14228082  0.24228082 -0.05771918]
 [ 0.1         0.2        -0.1       ]]
b2: [[ 0.05302131 -0.14697869]
 [ 0.14697869 -0.05302131]]
